### ISSUE TITLE
No readme

### ISSUE THREAD

**Issue by agatiwi** [marcol13/squash-tournament-website#2]
Where is the info what is that "squash" thingy???

Best regards,
Agata

**Comment by marcol13** [comment]
Hello @agatiwi,

I am so sorry about no information about that. Squash `is a racket and ball sport played by two or four players in a four-walled court with a small, hollow rubber ball. The players alternate in striking the ball with their rackets onto the playable surfaces of the four walls of the court.` and also `is a genus of herbaceous vegetables in the gourd family, Squash (also known as cucurbits or cucurbi) native to the Andes and Mesoamerica.`

Hope it helps,
Marcin Krueger
